(load "logic-puzzles.scm")

(define (who-is-my-father)
  (let ((gabrielle (amb 'moore 'downing 'hall 'hood 'parker))
        (lorna (amb 'moore 'downing 'hall 'hood 'parker))
        (rosalind (amb 'moore 'downing 'hall 'hood 'parker))
        (melissa (amb 'moore 'downing 'hall 'hood 'parker))
        (mary (amb 'moore 'downing 'hall 'hood 'parker)))
    (require
     (distinct? (list gabrielle lorna rosalind melissa mary)))
    (require (eq? melissa 'hood))
    (require (eq? mary 'moore))
    (require (not (eq? gabrielle 'hood)))
    (require (not (eq? lorna 'moore)))
    (require (not (eq? rosalind 'hall)))
    (require (not (eq? gabrielle 'parker)))
    (list (list 'gabrielle gabrielle)
          (list 'lorna lorna)
          (list 'rosalind rosalind)
          (list 'melissa melissa)
          (list 'mary mary))))
