(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define bad-password
    (let ((num-consecutive-failures 0))
      (lambda (amount)
        (begin (set! num-consecutive-failures (+ 1 num-consecutive-failures))
               (if (> num-consecutive-failures 7)
                   (call-the-cops)
                   "Incorrect password")))))
  (define dispatch
    (let ((num-bad-passwords 0))
      (lambda (p m)
        (if (eq? password p)
            (begin (set! num-bad-passwords 0)
                   (cond ((eq? m 'withdraw) withdraw)
                         ((eq? m 'deposit) deposit)
                         (else (error "Unknown request -- MAKE-ACCOUNT" m))))
            bad-password))))
  dispatch)
